update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -1,4 +1,3 @@
-# Mauro Sterckx
 name: Secure Python Pipeline
 
 on:
@@ -17,26 +16,36 @@ jobs:
   security-checks:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
-      - name: Set up Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: "3.x"
-      - name: Install dependencies
+      # Step 1: Clone application source code
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      # Step 2: Run Semgrep for Static Application Security Testing (SAST)
+      - name: Run full scan with Semgrep
         run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt
-      # - name: Test with pytest
-      #   run: |
-      #     pip install pytest pytest-cov
-      #     pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
+          semgrep --sarif --output report.sarif --metrics=off --config="p/default"
+        continue-on-error: false # Zorg ervoor dat de job faalt als Semgrep een probleem vindt
 
-      # Voeg CodeQL toe voor SAST
-      - name: Set up CodeQL
-        uses: github/codeql-action/setup # Correcte versie van setup
+      # Step 3: Save the report as an artifact
+      - name: Save report as pipeline artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: report.sarif
+          path: report.sarif
 
-      - name: Initialize CodeQL database
-        uses: github/codeql-action/autobuild@v2
+      # Step 4: Download the artifact (optioneel, kan nodig zijn voor later gebruik)
+      - name: Download report
+        uses: actions/download-artifact@v2
+        with:
+          name: report.sarif
 
-      - name: Run CodeQL analysis
-        uses: github/codeql-action/analyze@v2
+      # Step 5: Check the status of the scan and block PR if it fails
+      - name: Check Semgrep report status
+        run: |
+          if [ -f report.sarif ]; then
+            # Als er resultaten zijn, betekent dit dat er kwetsbaarheden zijn gevonden
+            jq '.results | length' report.sarif | grep -q '0' || exit 1
+          else
+            echo "Semgrep report not found, exiting"
+            exit 1
+        continue-on-error: false # Als er kwetsbaarheden zijn, zorgt dit ervoor dat de workflow faalt
